name: team_pampers
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  connectivity_plus:
  flutter_hooks:
  freezed:
  freezed_annotation:
  gap: ^3.0.1
  hooks_riverpod: ^2.4.0
  intl: ^0.18.1
  json_annotation:
  shared_preferences: ^2.2.1
  tuple: ^2.0.2
  flutter_spinkit: ^5.2.0
  firebase_core: ^2.16.0
  cloud_firestore: ^4.9.2
  firebase_auth: ^4.10.0
  firebase_storage: ^11.2.7
  flutter_animate: ^4.2.0+1
  lottie: ^2.6.0
  image_picker: ^1.0.4
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

flutter_gen:
  output: lib/utils/gen/
  colors: 
    inputs:
      - assets/colors/colors.xml
