// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvAlx_-Yk7Y4fcAXy0sT_qtTgkDQ4bMFU',
    appId: '1:613294581282:web:99c47212da37be19c90c7b',
    messagingSenderId: '613294581282',
    projectId: 'team-pampers',
    authDomain: 'team-pampers.firebaseapp.com',
    storageBucket: 'team-pampers.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqEYYfDw33wc50J7igXl7_jq3bAVLlNP8',
    appId: '1:613294581282:android:31b5f00c5b3f5ac0c90c7b',
    messagingSenderId: '613294581282',
    projectId: 'team-pampers',
    storageBucket: 'team-pampers.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC_y_HrRz2UZtK2Rs72RCVt5HEsnRx-Dw',
    appId: '1:613294581282:ios:5e63f7d5f30370fcc90c7b',
    messagingSenderId: '613294581282',
    projectId: 'team-pampers',
    storageBucket: 'team-pampers.appspot.com',
    iosBundleId: 'com.example.teamPampers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC_y_HrRz2UZtK2Rs72RCVt5HEsnRx-Dw',
    appId: '1:613294581282:ios:269990d6007ea775c90c7b',
    messagingSenderId: '613294581282',
    projectId: 'team-pampers',
    storageBucket: 'team-pampers.appspot.com',
    iosBundleId: 'com.example.teamPampers.RunnerTests',
  );
}
